-- Football Performance System
-- Core database schema v0.1
-- Target engine: DuckDB
-- IDs are generated by the application/import pipeline (UUID/string) to keep imports deterministic.

CREATE TABLE IF NOT EXISTS schema_meta (
    schema_version VARCHAR PRIMARY KEY,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR
);

INSERT INTO schema_meta (schema_version, description)
SELECT '0.1.0', 'Initial event-oriented core schema'
WHERE NOT EXISTS (
    SELECT 1 FROM schema_meta WHERE schema_version = '0.1.0'
);

-- ============================================================
-- MASTER DATA
-- ============================================================

CREATE TABLE IF NOT EXISTS teams (
    team_id VARCHAR PRIMARY KEY,
    display_name VARCHAR NOT NULL,
    source_name VARCHAR,
    source_team_id VARCHAR,
    is_anonymized BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS players (
    player_id VARCHAR PRIMARY KEY,
    display_name VARCHAR NOT NULL,
    source_name VARCHAR,
    source_player_id VARCHAR,
    default_position VARCHAR,
    is_anonymized BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matches (
    match_id VARCHAR PRIMARY KEY,
    competition VARCHAR,
    season VARCHAR,
    match_date TIMESTAMP,
    home_team_id VARCHAR,
    away_team_id VARCHAR,
    home_score INTEGER,
    away_score INTEGER,
    source_match_id VARCHAR,
    source_type VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (home_team_id) REFERENCES teams(team_id),
    FOREIGN KEY (away_team_id) REFERENCES teams(team_id)
);

-- ============================================================
-- MATCH CONTEXT
-- ============================================================

CREATE TABLE IF NOT EXISTS team_match (
    match_id VARCHAR NOT NULL,
    team_id VARCHAR NOT NULL,
    opponent_team_id VARCHAR,
    is_home BOOLEAN,
    starting_formation VARCHAR,
    score_for INTEGER,
    score_against INTEGER,
    PRIMARY KEY (match_id, team_id),
    FOREIGN KEY (match_id) REFERENCES matches(match_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (opponent_team_id) REFERENCES teams(team_id)
);

-- Main analytical unit of the project.
CREATE TABLE IF NOT EXISTS player_match (
    match_id VARCHAR NOT NULL,
    team_id VARCHAR NOT NULL,
    player_id VARCHAR NOT NULL,
    started BOOLEAN,
    minutes_played DOUBLE,
    primary_role VARCHAR,
    shirt_number INTEGER,
    PRIMARY KEY (match_id, player_id),
    FOREIGN KEY (match_id) REFERENCES matches(match_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (player_id) REFERENCES players(player_id)
);

-- Allows one player to change role/side/position during a match.
CREATE TABLE IF NOT EXISTS player_role_stints (
    stint_id VARCHAR PRIMARY KEY,
    match_id VARCHAR NOT NULL,
    team_id VARCHAR NOT NULL,
    player_id VARCHAR NOT NULL,
    start_second INTEGER NOT NULL,
    end_second INTEGER,
    role VARCHAR,
    position VARCHAR,
    side VARCHAR,
    formation VARCHAR,
    source_type VARCHAR,
    FOREIGN KEY (match_id) REFERENCES matches(match_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (player_id) REFERENCES players(player_id)
);

-- ============================================================
-- ATOMIC EVENTS
-- ============================================================

-- Stable event table. The event taxonomy can evolve without altering
-- the table structure: action_type + subtype + outcome are data, not columns.
CREATE TABLE IF NOT EXISTS match_events (
    event_id VARCHAR PRIMARY KEY,
    match_id VARCHAR NOT NULL,
    team_id VARCHAR NOT NULL,
    player_id VARCHAR,

    action_type VARCHAR NOT NULL,
    subtype VARCHAR,
    outcome VARCHAR,

    period INTEGER,
    match_second INTEGER,
    video_second DOUBLE,

    x DOUBLE,
    y DOUBLE,

    -- Optional controlled contextual labels. Keep sparse information here;
    -- important recurring fields should become explicit columns only after validation.
    qualifiers JSON,

    linked_event_id VARCHAR,
    source_type VARCHAR NOT NULL,
    source_event_id VARCHAR,
    collector_session_id VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (match_id) REFERENCES matches(match_id),
    FOREIGN KEY (team_id) REFERENCES teams(team_id),
    FOREIGN KEY (player_id) REFERENCES players(player_id)
);

CREATE INDEX IF NOT EXISTS idx_events_match ON match_events(match_id);
CREATE INDEX IF NOT EXISTS idx_events_player_match ON match_events(match_id, player_id);
CREATE INDEX IF NOT EXISTS idx_events_action ON match_events(action_type, subtype, outcome);

-- ============================================================
-- COLLECTOR TRACEABILITY
-- ============================================================

CREATE TABLE IF NOT EXISTS collector_sessions (
    collector_session_id VARCHAR PRIMARY KEY,
    match_id VARCHAR NOT NULL,
    collector_version VARCHAR,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    notes VARCHAR,
    FOREIGN KEY (match_id) REFERENCES matches(match_id)
);

-- ============================================================
-- GPS NORMALIZED LAYER
-- ============================================================

CREATE TABLE IF NOT EXISTS gps_imports (
    gps_import_id VARCHAR PRIMARY KEY,
    match_id VARCHAR,
    provider VARCHAR,
    source_filename VARCHAR,
    mapping_version VARCHAR,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (match_id) REFERENCES matches(match_id)
);

CREATE TABLE IF NOT EXISTS gps_observations (
    gps_import_id VARCHAR NOT NULL,
    match_id VARCHAR NOT NULL,
    player_id VARCHAR NOT NULL,
    timestamp_ms BIGINT NOT NULL,
    x DOUBLE,
    y DOUBLE,
    distance_m DOUBLE,
    speed_m_s DOUBLE,
    acceleration_m_s2 DOUBLE,
    PRIMARY KEY (gps_import_id, player_id, timestamp_ms),
    FOREIGN KEY (gps_import_id) REFERENCES gps_imports(gps_import_id),
    FOREIGN KEY (match_id) REFERENCES matches(match_id),
    FOREIGN KEY (player_id) REFERENCES players(player_id)
);

-- ============================================================
-- DERIVED DATA
-- ============================================================

-- Long-form feature store. No metric is approved merely by having a row here.
-- feature_version identifies the exact calculation logic used.
CREATE TABLE IF NOT EXISTS player_match_features (
    match_id VARCHAR NOT NULL,
    player_id VARCHAR NOT NULL,
    feature_name VARCHAR NOT NULL,
    feature_value DOUBLE,
    feature_text VARCHAR,
    feature_version VARCHAR NOT NULL,
    computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (match_id, player_id, feature_name, feature_version),
    FOREIGN KEY (match_id) REFERENCES matches(match_id),
    FOREIGN KEY (player_id) REFERENCES players(player_id)
);

-- Generic auditable outputs from expert rules or models.
CREATE TABLE IF NOT EXISTS decision_results (
    decision_id VARCHAR PRIMARY KEY,
    match_id VARCHAR,
    player_id VARCHAR,
    node_id VARCHAR,
    result_type VARCHAR NOT NULL,
    result_value VARCHAR,
    confidence DOUBLE,
    justification VARCHAR,
    engine_version VARCHAR NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (match_id) REFERENCES matches(match_id),
    FOREIGN KEY (player_id) REFERENCES players(player_id)
);

-- ============================================================
-- APPROVED DERIVED LOGIC
-- ============================================================

-- A failed pass or failed dribble already implies possession loss.
-- LOSS is reserved for turnovers not explained by those actions.
CREATE OR REPLACE VIEW v_possession_losses AS
SELECT
    event_id,
    match_id,
    team_id,
    player_id,
    match_second,
    CASE
        WHEN action_type = 'PASS' AND outcome = 'FAIL' THEN 'FAILED_PASS'
        WHEN action_type = 'DRIBBLE' AND outcome = 'FAIL' THEN 'FAILED_DRIBBLE'
        WHEN action_type = 'LOSS' THEN COALESCE(subtype, 'OTHER_TURNOVER')
        ELSE NULL
    END AS loss_reason
FROM match_events
WHERE
    (action_type = 'PASS' AND outcome = 'FAIL')
    OR (action_type = 'DRIBBLE' AND outcome = 'FAIL')
    OR action_type = 'LOSS';
